name: ideatrix.com
favicon: null
layout_spectrum: 0.9848
typography_spectrum: 0.4727681882213801
title: Strategic Idea Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5377ab'
    - '#080904'
    - '#b7b8bd'
    - '#f2c601'
    - '#444614'
  brandStrength: 0.25
  lightness: 0.5526776036713272
  saturation: 0.8487576523330063
  rhythmicContrast: 0.7262143711559474
purpose: []
