name: ideatrix.com
favicon: null
layout_spectrum: 0.9848
typography_spectrum: 0.4727681882213801
title: Strategic Idea Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ab2848'
    - '#ffffff'
    - '#202020'
    - '#410d17'
  brandStrength: 0.25
  lightness: 0.5526776036713272
  saturation: 0.8487576523330063
  rhythmicContrast: 0.7262143711559474
purpose: []
